### PR TITLE
Articles about routing in angular.

### PR DESCRIPTION
**Pull request by Enirate**
Thanks, here's my pull request. I've added the routing articles.

### CODE REVIEW

**Comment by ireade** [comment]
Thanks @Enirate ! A couple of things:

- You didn't add any of the Jekyll Front Matter. Check out the first few lines of the other posts to see what I'm talking about
- Please make sure that all titles are written in title case (not CAPS)

**Comment by ireade** [comment]
Hey @Enirate . After I merged I realised there were a number of formatting issues. Please test it out locally first before pushing.

**Comment by Enirate** [comment]
Hi Ire,
I'm sorry for that. I will try to figure out how to test .md files locally.
However if you know how I can test locally, I'd be grateful if I can learn
from you. Thanks a lot.

**Comment by ireade** [comment]
Hey @Enirate !

No problem. Basically you just need to have a version of this repository locally. Just clone this repository, and run `bundle install` (Assuming you have ruby and bundle on your machine already). You may also need to install jekyll, check out their site for that https://jekyllrb.com

Once that is done, run `jekyll serve` to start up the site locally. Then, you can make edits to your post files in the `_posts` directory. When everything looks nice, you can create a PR again.

**Pull request merged**
